version: '3'
services:
  lego-mongo:
    image: mongo:latest
    container_name: lego-mongo
    volumes:
      - /data/mongo/db:/data/db
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    ports:
      - 27017:27017
    env_file:
      - .env
  lego-redis:
    image: redis:6
    container_name: lego-redis
    volumes:
      - /data/redis/data:/data
      - /data/redis/logs:/logs
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    env_file:
      - .env
  lego-backend:
    image: registry.cn-chengdu.aliyuncs.com/jaquelee/h5brick:{{tag}}
    container_name: lego-backend
    ports:
     - 7002:7001
    env_file:
      - .env